In [2]:
import gymnasium as gym


In [3]:
env = gym.make("CartPole-v1", render_mode="human")

In [4]:

episodes = 5
for episode in range(1,episodes+1):
    state = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        action = env.action_space.sample()
        observation, reward, terminated, truncated, info = env.step(action)
        score += reward
        done = terminated or truncated
    print('Episode:{} Score:{}'.format(episode,score))    
env.close()

Episode:1 Score:21.0
Episode:2 Score:65.0
Episode:3 Score:19.0
Episode:4 Score:10.0
Episode:5 Score:17.0


In [14]:
print(env.action_space)
print(env.action_space.sample())

Discrete(2)
1


In [15]:
print(env.observation_space)
print(env.observation_space.sample())

Box([-4.8               -inf -0.41887903        -inf], [4.8               inf 0.41887903        inf], (4,), float32)
[-3.6526368  -0.859481   -0.34740335  0.45624673]


In [3]:
import os
log_path = os.path.join('Training','Logs')

In [4]:
log_path

'Training/Logs'

In [5]:
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

In [6]:
environment_name = "CartPole-v0"
env = gym.make(environment_name)
env = DummyVecEnv([lambda: env])
model = PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path)

/home/illusion/.local/lib/python3.10/site-packages/gymnasium/envs/registration.py:519: DeprecationWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.deprecation(


Using cpu device


In [24]:
PPO??

Init signature:
PPO(
    policy: Union[str, type[stable_baselines3.common.policies.ActorCriticPolicy]],
    env: Union[gymnasium.core.Env, ForwardRef('VecEnv'), str],
    learning_rate: Union[float, Callable[[float], float]] = 0.0003,
    n_steps: int = 2048,
    batch_size: int = 64,
    n_epochs: int = 10,
    gamma: float = 0.99,
    gae_lambda: float = 0.95,
    clip_range: Union[float, Callable[[float], float]] = 0.2,
    clip_range_vf: Union[NoneType, float, Callable[[float], float]] = None,
    normalize_advantage: bool = True,
    ent_coef: float = 0.0,
    vf_coef: float = 0.5,
    max_grad_norm: float = 0.5,
    use_sde: bool = False,
    sde_sample_freq: int = -1,
    rollout_buffer_class: Optional[type[stable_baselines3.common.buffers.RolloutBuffer]] = None,
    rollout_buffer_kwargs: Optional[dict[str, Any]] = None,
    target_kl: Optional[float] = None,
    stats_window_size: int = 100,
    tensorboard_log: Optional[str] = None,
    policy_kwargs: Optional[dict[str, Any]]

In [7]:
model.learn(total_timesteps=20000)

Logging to Training/Logs/PPO_11
-----------------------------
| time/              |      |
|    fps             | 2807 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2090        |
|    iterations           | 2           |
|    time_elapsed         | 1           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008980786 |
|    clip_fraction        | 0.0978      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | 0.00449     |
|    learning_rate        | 0.0003      |
|    loss                 | 5.26        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0152     |
|    value_loss           | 44          |
-----------------------------------------
--

In [22]:
PPO_Path = os.path.join('Training','Saved Models','PPO_Model_Cartpole')

In [23]:
model.save(PPO_Path)

In [8]:
env = gym.make(environment_name, render_mode="human")
evaluate_policy(model,env,n_eval_episodes=10,render=True)

/home/illusion/.local/lib/python3.10/site-packages/gymnasium/envs/registration.py:519: DeprecationWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.deprecation(
/home/illusion/.local/lib/python3.10/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


KeyboardInterrupt: 

In [9]:
env.close()

In [ ]:
obs, _ = env.reset()
action, _ = model.predict(obs)

action

array(1)

In [1]:
# Fix for the rendering issue
env = gym.make(environment_name, render_mode="human")  # Reinitialize the environment
episodes = 5
for episode in range(1, episodes + 1):
    obs, _ = env.reset()  # Reset the environment
    done = False
    score = 0

    while not done:
        try:
            env.render()  # Render the environment
        except Exception as e:
            print(f"Rendering error: {e}")
            break  # Exit the loop if rendering fails

        action, _ = model.predict(obs)  # Predict action using the model
        obs, reward, terminated, truncated, info = env.step(action)
        score += reward
        done = terminated or truncated

    print(f'Episode: {episode} Score: {score}')
env.close()

NameError: name 'gym' is not defined

In [30]:
env = gym.make("CartPole-v1", render_mode="human")  # recreate environment
obs, info = env.reset()  # now works again
print(obs)


[-0.02617642  0.02392025  0.04807609 -0.02237277]


In [31]:
action, _ = model.predict(obs)

In [32]:
env.action_space.sample()

np.int64(0)

In [36]:
env.step(action)

(array([-9.3199866e-04,  8.0194622e-01,  1.2980967e-02, -1.1391455e+00],
       dtype=float32),
 1.0,
 False,
 False,
 {})

In [37]:
env.close()  # close the environment

In [38]:
training_log_path = os.path.join(log_path, 'PPO_11')

In [39]:
training_log_path

'Training/Logs/PPO_11'

In [40]:
!tensorboard --logdir={training_log_path}

TensorFlow installation not found - running with reduced feature set.

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/issues/4784

Serving TensorBoard on localhost; to expose to the network, use a proxy or pass --bind_all
TensorBoard 2.19.0 at http://localhost:6006/ (Press CTRL+C to quit)
^C


In [47]:
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold
import os
env = gym.make("CartPole-v0")

/home/illusion/.local/lib/python3.10/site-packages/gymnasium/envs/registration.py:519: DeprecationWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.deprecation(


In [48]:
save_path = os.path.join('Training', 'Saved Models')

In [49]:
stop_callback = StopTrainingOnRewardThreshold(reward_threshold=200, verbose=1)
eval_callback = EvalCallback(env,
callback_on_new_best=stop_callback,
    eval_freq=10000,
    best_model_save_path=save_path,
    verbose=1
)

In [50]:
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [51]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to Training/Logs/PPO_12
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 23.5     |
|    ep_rew_mean     | 23.5     |
| time/              |          |
|    fps             | 2820     |
|    iterations      | 1        |
|    time_elapsed    | 0        |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 28.5        |
|    ep_rew_mean          | 28.5        |
| time/                   |             |
|    fps                  | 1961        |
|    iterations           | 2           |
|    time_elapsed         | 2           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008307628 |
|    clip_fraction        | 0.0833      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.687      |
|    explained_variance   | -0.00722    

/home/illusion/.local/lib/python3.10/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


Eval num_timesteps=10000, episode_reward=176.40 +/- 23.00
Episode length: 176.40 +/- 23.00
-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 176         |
|    mean_reward          | 176         |
| time/                   |             |
|    total_timesteps      | 10000       |
| train/                  |             |
|    approx_kl            | 0.006908298 |
|    clip_fraction        | 0.0447      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.62       |
|    explained_variance   | 0.332       |
|    learning_rate        | 0.0003      |
|    loss                 | 24.2        |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.012      |
|    value_loss           | 54.3        |
-----------------------------------------
New best mean reward!
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 64.1     |
|    ep_rew_mean     | 64.1  

In [52]:
net_arch = [dict(pi=[128,128,128,128],vf=[128,128,128,128])]

In [54]:
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path , policy_kwargs=dict(net_arch=net_arch))

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [55]:
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to Training/Logs/PPO_13
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 22.5     |
|    ep_rew_mean     | 22.5     |
| time/              |          |
|    fps             | 2342     |
|    iterations      | 1        |
|    time_elapsed    | 0        |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 28.8        |
|    ep_rew_mean          | 28.8        |
| time/                   |             |
|    fps                  | 1574        |
|    iterations           | 2           |
|    time_elapsed         | 2           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.015752481 |
|    clip_fraction        | 0.272       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.68       |
|    explained_variance   | -0.000666   

/home/illusion/.local/lib/python3.10/site-packages/stable_baselines3/common/evaluation.py:67: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


Eval num_timesteps=10000, episode_reward=200.00 +/- 0.00
Episode length: 200.00 +/- 0.00
-----------------------------------------
| eval/                   |             |
|    mean_ep_length       | 200         |
|    mean_reward          | 200         |
| time/                   |             |
|    total_timesteps      | 10000       |
| train/                  |             |
|    approx_kl            | 0.010130774 |
|    clip_fraction        | 0.126       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.577      |
|    explained_variance   | 0.465       |
|    learning_rate        | 0.0003      |
|    loss                 | 18          |
|    n_updates            | 40          |
|    policy_gradient_loss | -0.0185     |
|    value_loss           | 52.5        |
-----------------------------------------
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 74.1     |
|    ep_rew_mean     | 74.1     |
| time/            

In [56]:
from stable_baselines3 import DQN

In [57]:
model  = DQN('MlpPolicy', env, verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [58]:
model.learn(total_timesteps=20000)

Logging to Training/Logs/DQN_1
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 28       |
|    ep_rew_mean      | 28       |
|    exploration_rate | 0.947    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 3827     |
|    time_elapsed     | 0        |
|    total_timesteps  | 112      |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 0.498    |
|    n_updates        | 2        |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 32       |
|    ep_rew_mean      | 32       |
|    exploration_rate | 0.878    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 2573     |
|    time_elapsed     | 0        |
|    total_timesteps  | 256      |
| train/              |          |
|    learning_rate    | 0.0001   |
|    loss             | 